<template>
    <ConfigurableTable :columns="columns"
                       :items="items"
                       identifier-column="issues.id"
                       :loading="loading" />
</template>
  
<script>
import ConfigurableTable from './ConfigurableTable.vue'
  
export default {
    name: 'Issues',
    components: {
        ConfigurableTable
    },
    data() {
        return {
            columns: [
                {"label":"Name","key":"issues.name","type":"string"},
                {"label":"Issue members","key":"issue_members","type":"initialsRelationshipObject"},
                {"label":"Identifier","key":"issues.identifier","type":"copyInput"},
                {"label":"Start date","key":"issues.start_date","type":"string"},
                {"label":"Due date","key":"issues.due_date","type":"string"},
                {"label":"Task type","key":"taskType.name","type":"label"},
                {"label":"Task status","key":"taskStatus.name","type":"label"},
                {"label":"Task priority","key":"taskPriority.name","type":"label"},
                {"label":"Flow order","key":"issues.flow_order","type":"string"},
                {"label":"Estimated hours","key":"issues.estimated_hours","type":"string"},
                {"label":"Time spent","key":"issues.time_spent","type":"string"},
                {"label":"Time_remaining","key":"issues.time_remaining","type":"string"},
                {"label":"Created at","key":"issues.created_at","type":"string"},
                {"label":"Tags","key":"tags","type":"tagsRelationshipObject"}
            ],
            issues: [
                { "issues.name": "Test issue 1", "issues.identifier": "TI1", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:55", "issues.time_spent": "0:00", "issues.time_remaining": "0:55", "issues.created_at": "05/30/2023 08:36", "issues.id": 3, "taskType.name": "Issue", "taskStatus.name": "Completed", "taskPriority.name": "Normal", "tags": [{ "id": 5, "name": "test tag 24-05", "display_name": "test tag 24-05", "initials": "T", "color": "#64DD17" }, { "id": 111, "name": "testowoo", "display_name": "testowoo", "initials": "T", "color": "#311B92" }, { "id": 127, "name": "newtag999", "display_name": "newtag999", "initials": "N", "color": "#9C27B0" }], "issue_members": [{ "id": 233, "first_name": "Lara", "last_name": "Moreno", "display_name": "Lara Moreno", "initials": "LM", "color": "amber-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 246, "first_name": "Eliana", "last_name": "Goodman", "display_name": "Eliana Goodman", "initials": "EG", "color": "purple-lighten-4" }]},
                { "issues.name": "Test issue 2", "issues.identifier": "TI2", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 08:13", "issues.id": 9, "taskType.name": "Development", "taskStatus.name": "Cancelled", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 3", "issues.identifier": "TI3", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 14:01", "issues.id": 11, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 4", "issues.identifier": "TI4", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/16/2023 10:09", "issues.id": 44, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 5", "issues.identifier": "TI5", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/19/2023 09:20", "issues.id": 64, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 6", "issues.identifier": "TI6", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "3:41", "issues.time_remaining": "-3:41", "issues.created_at": "06/19/2023 14:59", "issues.id": 72, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 7", "issues.identifier": "TI7", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:25", "issues.id": 83, "taskType.name": "Issue", "taskStatus.name": "In progress", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 8", "issues.identifier": "TI8", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:31", "issues.id": 89, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 9", "issues.identifier": "TI9", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 3, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 91, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 10", "issues.identifier": "TI10", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 92, "taskType.name": "Analysis", "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }]},
                { "issues.name": "Test issue 1", "issues.identifier": "TI1", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:55", "issues.time_spent": "0:00", "issues.time_remaining": "0:55", "issues.created_at": "05/30/2023 08:36", "issues.id": 100, "taskType.name": "Issue", "taskStatus.name": "Completed", "taskPriority.name": "Normal", "tags": [{ "id": 5, "name": "test tag 24-05", "display_name": "test tag 24-05", "initials": "T", "color": "#64DD17" }, { "id": 111, "name": "testowoo", "display_name": "testowoo", "initials": "T", "color": "#311B92" }, { "id": 127, "name": "newtag999", "display_name": "newtag999", "initials": "N", "color": "#9C27B0" }], "issue_members": [{ "id": 233, "first_name": "Lara", "last_name": "Moreno", "display_name": "Lara Moreno", "initials": "LM", "color": "amber-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 246, "first_name": "Eliana", "last_name": "Goodman", "display_name": "Eliana Goodman", "initials": "EG", "color": "purple-lighten-4" }]},
                { "issues.name": "Test issue 2", "issues.identifier": "TI2", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 08:13", "issues.id": 101, "taskType.name": "Development", "taskStatus.name": "Cancelled", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 3", "issues.identifier": "TI3", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 14:01", "issues.id": 102, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 4", "issues.identifier": "TI4", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/16/2023 10:09", "issues.id": 114, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 5", "issues.identifier": "TI5", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/19/2023 09:20", "issues.id": 120, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 6", "issues.identifier": "TI6", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "3:41", "issues.time_remaining": "-3:41", "issues.created_at": "06/19/2023 14:59", "issues.id": 136, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 7", "issues.identifier": "TI7", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:25", "issues.id": 139, "taskType.name": "Issue", "taskStatus.name": "In progress", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 8", "issues.identifier": "TI8", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:31", "issues.id": 141, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 9", "issues.identifier": "TI9", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 3, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 142, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 10", "issues.identifier": "TI10", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 143, "taskType.name": "Analysis", "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }]},
                { "issues.name": "Test issue 1", "issues.identifier": "TI1", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:55", "issues.time_spent": "0:00", "issues.time_remaining": "0:55", "issues.created_at": "05/30/2023 08:36", "issues.id": 145, "taskType.name": "Issue", "taskStatus.name": "Completed", "taskPriority.name": "Normal", "tags": [{ "id": 5, "name": "test tag 24-05", "display_name": "test tag 24-05", "initials": "T", "color": "#64DD17" }, { "id": 111, "name": "testowoo", "display_name": "testowoo", "initials": "T", "color": "#311B92" }, { "id": 127, "name": "newtag999", "display_name": "newtag999", "initials": "N", "color": "#9C27B0" }], "issue_members": [{ "id": 233, "first_name": "Lara", "last_name": "Moreno", "display_name": "Lara Moreno", "initials": "LM", "color": "amber-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 246, "first_name": "Eliana", "last_name": "Goodman", "display_name": "Eliana Goodman", "initials": "EG", "color": "purple-lighten-4" }]},
                { "issues.name": "Test issue 2", "issues.identifier": "TI2", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 08:13", "issues.id": 153, "taskType.name": "Development", "taskStatus.name": "Cancelled", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 3", "issues.identifier": "TI3", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 14:01", "issues.id": 154, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 4", "issues.identifier": "TI4", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/16/2023 10:09", "issues.id": 165, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 5", "issues.identifier": "TI5", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/19/2023 09:20", "issues.id": 194, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 6", "issues.identifier": "TI6", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "3:41", "issues.time_remaining": "-3:41", "issues.created_at": "06/19/2023 14:59", "issues.id": 197, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 7", "issues.identifier": "TI7", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:25", "issues.id": 198, "taskType.name": "Issue", "taskStatus.name": "In progress", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 8", "issues.identifier": "TI8", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:31", "issues.id": 199, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 9", "issues.identifier": "TI9", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 3, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 200, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 10", "issues.identifier": "TI10", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 219, "taskType.name": "Analysis", "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }]},
                { "issues.name": "Test issue 1", "issues.identifier": "TI1", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:55", "issues.time_spent": "0:00", "issues.time_remaining": "0:55", "issues.created_at": "05/30/2023 08:36", "issues.id": 220, "taskType.name": "Issue", "taskStatus.name": "Completed", "taskPriority.name": "Normal", "tags": [{ "id": 5, "name": "test tag 24-05", "display_name": "test tag 24-05", "initials": "T", "color": "#64DD17" }, { "id": 111, "name": "testowoo", "display_name": "testowoo", "initials": "T", "color": "#311B92" }, { "id": 127, "name": "newtag999", "display_name": "newtag999", "initials": "N", "color": "#9C27B0" }], "issue_members": [{ "id": 233, "first_name": "Lara", "last_name": "Moreno", "display_name": "Lara Moreno", "initials": "LM", "color": "amber-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 246, "first_name": "Eliana", "last_name": "Goodman", "display_name": "Eliana Goodman", "initials": "EG", "color": "purple-lighten-4" }]},
                { "issues.name": "Test issue 2", "issues.identifier": "TI2", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 08:13", "issues.id": 222, "taskType.name": "Development", "taskStatus.name": "Cancelled", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 3", "issues.identifier": "TI3", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 14:01", "issues.id": 223, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 4", "issues.identifier": "TI4", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/16/2023 10:09", "issues.id": 224, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 5", "issues.identifier": "TI5", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/19/2023 09:20", "issues.id": 225, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 6", "issues.identifier": "TI6", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "3:41", "issues.time_remaining": "-3:41", "issues.created_at": "06/19/2023 14:59", "issues.id": 237, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 7", "issues.identifier": "TI7", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:25", "issues.id": 248, "taskType.name": "Issue", "taskStatus.name": "In progress", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 8", "issues.identifier": "TI8", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:31", "issues.id": 251, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 9", "issues.identifier": "TI9", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 3, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 252, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 10", "issues.identifier": "TI10", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 254, "taskType.name": "Analysis", "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }]},
                { "issues.name": "Test issue 1", "issues.identifier": "TI1", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:55", "issues.time_spent": "0:00", "issues.time_remaining": "0:55", "issues.created_at": "05/30/2023 08:36", "issues.id": 263, "taskType.name": "Issue", "taskStatus.name": "Completed", "taskPriority.name": "Normal", "tags": [{ "id": 5, "name": "test tag 24-05", "display_name": "test tag 24-05", "initials": "T", "color": "#64DD17" }, { "id": 111, "name": "testowoo", "display_name": "testowoo", "initials": "T", "color": "#311B92" }, { "id": 127, "name": "newtag999", "display_name": "newtag999", "initials": "N", "color": "#9C27B0" }], "issue_members": [{ "id": 233, "first_name": "Lara", "last_name": "Moreno", "display_name": "Lara Moreno", "initials": "LM", "color": "amber-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 246, "first_name": "Eliana", "last_name": "Goodman", "display_name": "Eliana Goodman", "initials": "EG", "color": "purple-lighten-4" }]},
                { "issues.name": "Test issue 2", "issues.identifier": "TI2", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 08:13", "issues.id": 289, "taskType.name": "Development", "taskStatus.name": "Cancelled", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 3", "issues.identifier": "TI3", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 2, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/02/2023 14:01", "issues.id": 302, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 4", "issues.identifier": "TI4", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/16/2023 10:09", "issues.id": 303, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 5", "issues.identifier": "TI5", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/19/2023 09:20", "issues.id": 309, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 6", "issues.identifier": "TI6", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "3:41", "issues.time_remaining": "-3:41", "issues.created_at": "06/19/2023 14:59", "issues.id": 311, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 7", "issues.identifier": "TI7", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": null, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:25", "issues.id": 312, "taskType.name": "Issue", "taskStatus.name": "In progress", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }]},
                { "issues.name": "Test issue 8", "issues.identifier": "TI8", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 5, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:31", "issues.id": 320, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": []},
                { "issues.name": "Test issue 9", "issues.identifier": "TI9", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 3, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 322, "taskType.name": null, "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 9, "first_name": "Daisy", "last_name": "Skinner", "display_name": "Daisy Skinner", "initials": "DS", "color": "brown-lighten-4" }]},
                { "issues.name": "Test issue 10", "issues.identifier": "TI10", "issues.start_date": { "value": null, "icon": null, "tooltip": null }, "issues.due_date": { "value": null, "icon": null, "tooltip": null }, "issues.flow_order": 4, "issues.estimated_hours": "0:00", "issues.time_spent": "0:00", "issues.time_remaining": "0:00", "issues.created_at": "06/20/2023 08:58", "issues.id": 323, "taskType.name": "Analysis", "taskStatus.name": "New", "taskPriority.name": "Normal", "tags": [], "issue_members": [{ "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }]},
            ],
            items: [],
            loading: false
        }
    },
    mounted() {
        this.loading = true
        setTimeout(() => {
            this.items = this.issues
            this.loading = false
        }, 1000)
    }
}
</script>
  