<template>
  <ConfigurableTable :columns="columns"
                     :items="items"
                     identifier-column="projects.id"
                     :loading="loading" />
</template>

<script>
import ConfigurableTable from './ConfigurableTable.vue'

export default {
    name: 'Projects',
    components: {
        ConfigurableTable
    },
    data() {
        return {
            columns: [
                {"label":"Name","key":"projects.name","type":"string"},
                {"label":"Workflow count","key":"workflow_count","type":"string"},
                {"label":"Identifier","key":"projects.identifier","type":"copyInput"},
                {"label":"Status name","key":"projectStatus.name","type":"label"},
                {"label":"Start at","key":"projects.start_at","type":"string"},
                {"label":"Time spent","key":"projects.time_spent","type":"string"},
                {"label":"Time remaining","key":"projects.time_remaining","type":"string"},
                {"label":"Created at","key":"projects.created_at","type":"string"},
                {"label":"Children count","key":"children_count","type":"string"},
                {"label":"Members","key":"members","type":"initialsRelationshipObject"},
                {"label":"Tags","key":"tags","type":"tagsRelationshipObject"},
                {"label":"Account name","key":"account.name","type":"string"}
            ],
            projects: [
                { "projects.name": "Test project 1", "projects.identifier": "TP1", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "10/13/2023 15:36", "projects.id": 368, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "8 / 2 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": [{ "id": 135, "name": "br", "display_name": "br", "initials": "B", "color": "#F50057" }, { "id": 136, "name": "now", "display_name": "now", "initials": "N", "color": "#FF6F00" }]},
                { "projects.name": "Test project 2", "projects.identifier": "TP2", "projects.start_at": { "value": "01/11/2024", "icon": "alert-circle-outline", "tooltip": "173 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/23/2024 09:51", "projects.id": 506, "account.name": "Test Company 1", "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }]},
                { "projects.name": "Test project 3", "projects.identifier": "TP3", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "11/20/2023 11:44", "projects.id": 386, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 4", "projects.identifier": "TP4", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "04/03/2024 15:01", "projects.id": 665, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "3 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 5", "projects.identifier": "TP5", "projects.start_at": { "value": "10/02/2023", "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "06/20/2023 08:46", "projects.id": 114, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "2 / 1 / 0", "members": [], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }, { "id": 54, "name": "00", "display_name": "00", "initials": "0", "color": "#FF6F00" }]},
                { "projects.name": "Test project 6", "projects.identifier": "TP6", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "03/20/2024 08:24", "projects.id": 646, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 7", "projects.identifier": "TP7", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "53:35", "projects.time_remaining": "-50:05", "projects.created_at": "06/19/2023 14:58", "projects.id": 103, "account.name": "Test company 2", "projectStatus.name": "Completed", "children_count": 3, "workflow_count": "2 / 3 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 8", "projects.identifier": "TP8", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "06/21/2023 13:16", "projects.id": 107, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "4 / 4 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 9", "projects.identifier": "TP9", "projects.start_at": { "value": "01/01/2024", "icon": "alert-circle-outline", "tooltip": "183 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/02/2024 11:56", "projects.id": 503, "account.name": null, "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": []},
                { "projects.name": "Test project 10", "projects.identifier": "TP10", "projects.start_at": { "value": "07/20/2023", "icon": "alert-circle-outline", "tooltip": "15 days" }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "01/04/2024 14:34", "projects.id": 515, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [], "tags": [{ "id": 1, "name": "Tag 1", "display_name": "Tag 1", "initials": "T1", "color": "#FF0000" }, { "id": 2, "name": "Tag 2", "display_name": "Tag 2", "initials": "T2", "color": "#00FF00" }]},
                { "projects.name": "Test project 1", "projects.identifier": "TP1", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "10/13/2023 15:36", "projects.id": 507, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "8 / 2 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": [{ "id": 135, "name": "br", "display_name": "br", "initials": "B", "color": "#F50057" }, { "id": 136, "name": "now", "display_name": "now", "initials": "N", "color": "#FF6F00" }]},
                { "projects.name": "Test project 2", "projects.identifier": "TP2", "projects.start_at": { "value": "01/11/2024", "icon": "alert-circle-outline", "tooltip": "173 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/23/2024 09:51", "projects.id": 590, "account.name": "Test Company 1", "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }]},
                { "projects.name": "Test project 3", "projects.identifier": "TP3", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "11/20/2023 11:44", "projects.id": 704, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 4", "projects.identifier": "TP4", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "04/03/2024 15:01", "projects.id": 155, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "3 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 5", "projects.identifier": "TP5", "projects.start_at": { "value": "10/02/2023", "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "06/20/2023 08:46", "projects.id": 501, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "2 / 1 / 0", "members": [], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }, { "id": 54, "name": "00", "display_name": "00", "initials": "0", "color": "#FF6F00" }]},
                { "projects.name": "Test project 6", "projects.identifier": "TP6", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "03/20/2024 08:24", "projects.id": 715, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 7", "projects.identifier": "TP7", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "53:35", "projects.time_remaining": "-50:05", "projects.created_at": "06/19/2023 14:58", "projects.id": 589, "account.name": "Test company 2", "projectStatus.name": "Completed", "children_count": 3, "workflow_count": "2 / 3 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 8", "projects.identifier": "TP8", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "06/21/2023 13:16", "projects.id": 300, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "4 / 4 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 9", "projects.identifier": "TP9", "projects.start_at": { "value": "01/01/2024", "icon": "alert-circle-outline", "tooltip": "183 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/02/2024 11:56", "projects.id": 716, "account.name": null, "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": []},
                { "projects.name": "Test project 10", "projects.identifier": "TP10", "projects.start_at": { "value": "07/20/2023", "icon": "alert-circle-outline", "tooltip": "15 days" }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "01/04/2024 14:34", "projects.id": 714, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [], "tags": [{ "id": 1, "name": "Tag 1", "display_name": "Tag 1", "initials": "T1", "color": "#FF0000" }, { "id": 2, "name": "Tag 2", "display_name": "Tag 2", "initials": "T2", "color": "#00FF00" }]},
                { "projects.name": "Test project 1", "projects.identifier": "TP1", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "10/13/2023 15:36", "projects.id": 279, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "8 / 2 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": [{ "id": 135, "name": "br", "display_name": "br", "initials": "B", "color": "#F50057" }, { "id": 136, "name": "now", "display_name": "now", "initials": "N", "color": "#FF6F00" }]},
                { "projects.name": "Test project 2", "projects.identifier": "TP2", "projects.start_at": { "value": "01/11/2024", "icon": "alert-circle-outline", "tooltip": "173 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/23/2024 09:51", "projects.id": 277, "account.name": "Test Company 1", "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }]},
                { "projects.name": "Test project 3", "projects.identifier": "TP3", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "11/20/2023 11:44", "projects.id": 388, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 4", "projects.identifier": "TP4", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "04/03/2024 15:01", "projects.id": 695, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "3 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 5", "projects.identifier": "TP5", "projects.start_at": { "value": "10/02/2023", "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "06/20/2023 08:46", "projects.id": 126, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "2 / 1 / 0", "members": [], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }, { "id": 54, "name": "00", "display_name": "00", "initials": "0", "color": "#FF6F00" }]},
                { "projects.name": "Test project 6", "projects.identifier": "TP6", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "03/20/2024 08:24", "projects.id": 666, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 7", "projects.identifier": "TP7", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "53:35", "projects.time_remaining": "-50:05", "projects.created_at": "06/19/2023 14:58", "projects.id": 601, "account.name": "Test company 2", "projectStatus.name": "Completed", "children_count": 3, "workflow_count": "2 / 3 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 8", "projects.identifier": "TP8", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "06/21/2023 13:16", "projects.id": 713, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "4 / 4 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 9", "projects.identifier": "TP9", "projects.start_at": { "value": "01/01/2024", "icon": "alert-circle-outline", "tooltip": "183 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/02/2024 11:56", "projects.id": 712, "account.name": null, "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": []},
                { "projects.name": "Test project 10", "projects.identifier": "TP10", "projects.start_at": { "value": "07/20/2023", "icon": "alert-circle-outline", "tooltip": "15 days" }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "01/04/2024 14:34", "projects.id": 703, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [], "tags": [{ "id": 1, "name": "Tag 1", "display_name": "Tag 1", "initials": "T1", "color": "#FF0000" }, { "id": 2, "name": "Tag 2", "display_name": "Tag 2", "initials": "T2", "color": "#00FF00" }]},
                { "projects.name": "Test project 1", "projects.identifier": "TP1", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "10/13/2023 15:36", "projects.id": 597, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "8 / 2 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": [{ "id": 135, "name": "br", "display_name": "br", "initials": "B", "color": "#F50057" }, { "id": 136, "name": "now", "display_name": "now", "initials": "N", "color": "#FF6F00" }]},
                { "projects.name": "Test project 2", "projects.identifier": "TP2", "projects.start_at": { "value": "01/11/2024", "icon": "alert-circle-outline", "tooltip": "173 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/23/2024 09:51", "projects.id": 598, "account.name": "Test Company 1", "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }]},
                { "projects.name": "Test project 3", "projects.identifier": "TP3", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "11/20/2023 11:44", "projects.id": 423, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 4", "projects.identifier": "TP4", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "04/03/2024 15:01", "projects.id": 454, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "3 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 5", "projects.identifier": "TP5", "projects.start_at": { "value": "10/02/2023", "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "06/20/2023 08:46", "projects.id": 636, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "2 / 1 / 0", "members": [], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }, { "id": 54, "name": "00", "display_name": "00", "initials": "0", "color": "#FF6F00" }]},
                { "projects.name": "Test project 6", "projects.identifier": "TP6", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "03/20/2024 08:24", "projects.id": 363, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 7", "projects.identifier": "TP7", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "53:35", "projects.time_remaining": "-50:05", "projects.created_at": "06/19/2023 14:58", "projects.id": 354, "account.name": "Test company 2", "projectStatus.name": "Completed", "children_count": 3, "workflow_count": "2 / 3 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 8", "projects.identifier": "TP8", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "06/21/2023 13:16", "projects.id": 115, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "4 / 4 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 9", "projects.identifier": "TP9", "projects.start_at": { "value": "01/01/2024", "icon": "alert-circle-outline", "tooltip": "183 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/02/2024 11:56", "projects.id": 338, "account.name": null, "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": []},
                { "projects.name": "Test project 10", "projects.identifier": "TP10", "projects.start_at": { "value": "07/20/2023", "icon": "alert-circle-outline", "tooltip": "15 days" }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "01/04/2024 14:34", "projects.id": 7, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [], "tags": [{ "id": 1, "name": "Tag 1", "display_name": "Tag 1", "initials": "T1", "color": "#FF0000" }, { "id": 2, "name": "Tag 2", "display_name": "Tag 2", "initials": "T2", "color": "#00FF00" }]},
                { "projects.name": "Test project 1", "projects.identifier": "TP1", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "10/13/2023 15:36", "projects.id": 523, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "8 / 2 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": [{ "id": 135, "name": "br", "display_name": "br", "initials": "B", "color": "#F50057" }, { "id": 136, "name": "now", "display_name": "now", "initials": "N", "color": "#FF6F00" }]},
                { "projects.name": "Test project 2", "projects.identifier": "TP2", "projects.start_at": { "value": "01/11/2024", "icon": "alert-circle-outline", "tooltip": "173 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/23/2024 09:51", "projects.id": 276, "account.name": "Test Company 1", "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }]},
                { "projects.name": "Test project 3", "projects.identifier": "TP3", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "11/20/2023 11:44", "projects.id": 327, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }, { "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 4", "projects.identifier": "TP4", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "04/03/2024 15:01", "projects.id": 355, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "3 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 5", "projects.identifier": "TP5", "projects.start_at": { "value": "10/02/2023", "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "06/20/2023 08:46", "projects.id": 360, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "2 / 1 / 0", "members": [], "tags": [{ "id": 3, "name": "000", "display_name": "000", "initials": "0", "color": "#E91E63" }, { "id": 54, "name": "00", "display_name": "00", "initials": "0", "color": "#FF6F00" }]},
                { "projects.name": "Test project 6", "projects.identifier": "TP6", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "03/20/2024 08:24", "projects.id": 362, "account.name": null, "projectStatus.name": null, "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 7", "projects.identifier": "TP7", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "53:35", "projects.time_remaining": "-50:05", "projects.created_at": "06/19/2023 14:58", "projects.id": 366, "account.name": "Test company 2", "projectStatus.name": "Completed", "children_count": 3, "workflow_count": "2 / 3 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 8", "projects.identifier": "TP8", "projects.start_at": { "value": null, "icon": null, "tooltip": null }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "06/21/2023 13:16", "projects.id": 625, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "4 / 4 / 1", "members": [{ "id": 8, "first_name": "Theo", "last_name": "Bowers", "display_name": "Theo Bowers", "initials": "TB", "color": "blue-lighten-4" }], "tags": []},
                { "projects.name": "Test project 9", "projects.identifier": "TP9", "projects.start_at": { "value": "01/01/2024", "icon": "alert-circle-outline", "tooltip": "183 days" }, "projects.time_spent": "0:00", "projects.time_remaining": "0:00", "projects.created_at": "01/02/2024 11:56", "projects.id": 627, "account.name": null, "projectStatus.name": "New", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [{ "id": 1, "first_name": "Kitty", "last_name": "Bright", "display_name": "Kitty Bright", "initials": "KB", "color": "teal-lighten-4" }, { "id": 2, "first_name": "Jaxon", "last_name": "Stephenson", "display_name": "Jaxon Stephenson", "initials": "JS", "color": "orange-lighten-4" }], "tags": []},
                { "projects.name": "Test project 10", "projects.identifier": "TP10", "projects.start_at": { "value": "07/20/2023", "icon": "alert-circle-outline", "tooltip": "15 days" }, "projects.time_spent": "123:00", "projects.time_remaining": "-123:00", "projects.created_at": "01/04/2024 14:34", "projects.id": 117, "account.name": null, "projectStatus.name": "In progress", "children_count": 0, "workflow_count": "0 / 0 / 0", "members": [], "tags": [{ "id": 1, "name": "Tag 1", "display_name": "Tag 1", "initials": "T1", "color": "#FF0000" }, { "id": 2, "name": "Tag 2", "display_name": "Tag 2", "initials": "T2", "color": "#00FF00" }]},
            ],
            items: [],
            loading: false
        }
    },
    mounted() {
        this.loading = true
        setTimeout(() => {
            this.items = this.projects
            this.loading = false
        }, 1000)
    }
}
</script>
